AWSTemplateFormatVersion: "2010-09-09"
Metadata:
    Generator: "Claudio Cordova"
Description: ""


Parameters:
  Image:
    Type: String
    Description: the build Image


#Task is stopping
#ResourceInitializationError: failed to validate logger args: create stream has been retried 1 times: failed to create Cloudwatch log stream: ResourceNotFoundException: The specified log group does not exist. : exit status 1


Resources:
    ECSTaskDefinition:
        Type: "AWS::ECS::TaskDefinition"
        Properties:
            ContainerDefinitions: 
              - 
                Essential: true
                #Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/pokerhandanalyzerapi:16ae14c6"
                Image: !Ref 'Image' 
                LogConfiguration: 
                    LogDriver: "awslogs"
                    Options: 
                        awslogs-group: "/ecs/poker-analyzer-service"
                        awslogs-region: !Ref AWS::Region
                        awslogs-stream-prefix: "ecs"
                Name: "poker-analyzer-service-container"
                PortMappings: 
                  - 
                    ContainerPort: 8080
                    HostPort: 8080
                    Protocol: "tcp"
            Family: "poker-analyzer-service-task-definition"
            TaskRoleArn: !GetAtt IAMRole.Arn
            ExecutionRoleArn: !GetAtt IAMRole.Arn
            NetworkMode: "awsvpc"
            RequiresCompatibilities: 
              - "FARGATE"
            Cpu: "256"
            Memory: "512"
    IAMRole:
        Type: "AWS::IAM::Role"
        Properties:
            Path: "/"
            RoleName: "poker-analyzer-service-task-definition-execution-role"
            AssumeRolePolicyDocument: "{\"Version\":\"2008-10-17\",\"Statement\":[{\"Sid\":\"\",\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"ecs-tasks.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
            MaxSessionDuration: 3600
            ManagedPolicyArns: 
              - "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
              - "arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess"
              - "arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess"

    MyLogGroup:
        Type: 'AWS::Logs::LogGroup'
        Properties:
          LogGroupName: /ecs/poker-analyzer-service
          RetentionInDays: 30              
          
          
Outputs:
  PokerAnalyzerTaskDefinitionArn:
    Description: poker-analyzer-service-task-definition ARN
    Export:          
      Name: PokerAnalyzerTaskDefinitionArn  
    Value: !Ref ECSTaskDefinition
  