---

apiVersion: v1
kind: Namespace
metadata:
  name: claudio-namespace

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: claudio-namespace
  name: claudio-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: claudio-container
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: claudio-container
    spec:
      containers:
      - image: CONTAINER_IMAGE
        imagePullPolicy: Always
        name: claudio-container
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 256Mi
---

apiVersion: v1
kind: Service
metadata:
  namespace: claudio-namespace
  name: claudio-service
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: claudio-container



---
# https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/


apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: claudio-hpa
  namespace: claudio-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: claudio-deployment
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50                            